### ISSUE TITLE
hirak/prestissimo issue with composer v2

### ISSUE THREAD

**Issue by DylanGD** [docusign/code-examples-php#14] opened 2020-11-10 23:26 UTC
Please remove hirak/prestissimo dependency, composer v2 does not support it and it's not more really necessary.
![composer_break](https://user-images.githubusercontent.com/5663375/98745806-8822ce80-23b4-11eb-8aa2-121035af89fc.png)

**Comment by LarryKlugerDS** [comment] 2020-11-12 07:02
Duplicate of # https://github.com/docusign/docusign-php-client/issues/123

**Closed as completed** 2020-11-12 07:03 UTC
Labels: duplicate, responded, question
